---
title: "Исключения и обработка исключений (Руководство по программированию в C#) | Microsoft Docs"
ms.custom: ""
ms.date: "11/24/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: ""
ms.topic: "article"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "C# - язык, исключения"
  - "обработка исключений [C#]"
  - "исключения [C#]"
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
caps.latest.revision: 33
caps.handback.revision: 33
author: "BillWagner"
ms.author: "wiwagn"
manager: "wpickett"
translationtype: Human Translation
---
# Исключения и обработка исключений (Руководство по программированию в C#)
[!INCLUDE[vs2017banner](../../../csharp/includes/vs2017banner.md)]

Функции обработки исключений на языке C\# помогают обрабатывать любые непредвиденные или исключительные ситуации, происходящие при выполнении программы.  При обработке исключений используются ключевые слова `try`, `catch` и `finally` для попыток применения действий, которые могут не достичь успеха, для обработки ошибок, если предполагается, что это может быть разумным, и для последующего освобождения ресурсов.  Исключения могут генерироваться средой CLR, платформой .NET Framework или внешними библиотеками, либо кодом приложения.  Исключения создаются при помощи ключевого слова `throw`.  
  
 Во многих случаях исключение может инициироваться не методом, вызванным непосредственно кодом, а другим методом, расположенным ниже в стеке вызовов.  Когда это происходит, среда CLR выполняет откат стека в поисках метода с блоком `catch` для определенного типа исключения. При обнаружении первого такого блока `catch` этот блок выполняется.  Если среда CLR не находит соответствующего блока `catch` где\-либо в стеке вызовов, она завершает процесс и отображает пользователю сообщение.  
  
 В этом примере метод тестирует деление на ноль и выполняет перехват соответствующей ошибки.  Без обработки исключений эта программа была бы завершена с ошибкой **DivideByZeroException was unhandled** \(не обработано исключение "деление на ноль"\).  
  
 [!CODE [csProgGuideExceptions#18](../CodeSnippet/VS_Snippets_VBCSharp/csProgGuideExceptions#18)]  
  
## Общие сведения об исключениях  
 Исключения имеют следующие свойства.  
  
-   Исключения имеют типы, в конечном счете являющиеся производными от `System.Exception`.  
  
-   Следует использовать блок `try` для заключения в него инструкций, которые могут выдать исключения.  
  
-   При возникновении исключения в блоке `try` поток управления немедленно переходит к первому соответствующему обработчику исключений, присутствующему в стеке вызовов.  В языке C\# ключевое слово `catch` используется для определения обработчика исключений.  
  
-   Если обработчик для определенного исключения не существует, выполнение программы завершается с сообщением об ошибке.  
  
-   Не перехватывайте исключение, если его нельзя обработать, и оставьте приложение в известном состоянии.  При перехвате `System.Exception` вновь инициируйте это исключение с использованием ключевого слова `throw` в конце блока `catch`.  
  
-   Если в блоке `catch` определяется переменная исключения, ее можно использовать для получения дополнительной информации о типе произошедшего исключения.  
  
-   Исключения могут явно генерироваться программной с помощью ключевого слова `throw`.  
  
-   Объекты исключения содержат подробные сведения об ошибке, такие как состояние стека вызовов и текстовое описание ошибки.  
  
-   Код в блоке `finally` выполняется, даже при возникновении исключения.  Блок `finally` используется для освобождения ресурсов, например для закрытия потоков или файлов, открытых в блоке `try`.  
  
-   Управляемые исключения в платформе .NET Framework реализуются в начале механизма структурированной обработки исключений Win32.  Дополнительные сведения см. в разделе [Структурированная обработка исключений](/visual-cpp/cpp/structured-exception-handling-c-cpp) и в документе [Подробное руководство по структурированной обработке исключений Win32](http://go.microsoft.com/fwlink/?LinkId=119654).  
  
## Связанные разделы  
 Дополнительные сведения об исключениях и обработке исключений см. в следующих разделах:  
  
-   [Использование исключений](../../../csharp/programming-guide/exceptions/using-exceptions.md)  
  
-   [Обработка исключений](../../../csharp/programming-guide/exceptions/exception-handling.md)  
  
-   [Создание и генерация исключений](../../../csharp/programming-guide/exceptions/creating-and-throwing-exceptions.md)  
  
-   [Исключения, создаваемые компилятором](../../../csharp/programming-guide/exceptions/compiler-generated-exceptions.md)  
  
-   [Практическое руководство. Обработка исключений с помощью блока try\-catch](../../../csharp/programming-guide/exceptions/how-to-handle-an-exception-using-try-catch.md)  
  
-   [Практическое руководство. Выполнение кода очистки с использованием блока finally](../../../csharp/programming-guide/exceptions/how-to-execute-cleanup-code-using-finally.md)  
  
## Спецификация языка C\#  
 [!INCLUDE[CSharplangspec](../../../csharp/language-reference/keywords/includes/csharplangspec_md.md)]  
  
## См. также  
 <xref:System.SystemException>   
 [Руководство по программированию на C\#](../../../csharp/programming-guide/index.md)   
 [Ключевые слова C\#](../../../csharp/language-reference/keywords/index.md)   
 [throw](../../../csharp/language-reference/keywords/throw.md)   
 [try\-catch](../../../csharp/language-reference/keywords/try-catch.md)   
 [try\-finally](../../../csharp/language-reference/keywords/try-finally.md)   
 [try\-catch\-finally](../../../csharp/language-reference/keywords/try-catch-finally.md)   
 [Исключения](../Topic/Handling%20and%20Throwing%20Exceptions.md)   
 [Иерархия исключений](../Topic/Exception%20Hierarchy.md)   
 [Написание надежного кода .NET](http://go.microsoft.com/fwlink/?LinkId=112400)   
 [Minidumps для конкретных исключений](http://go.microsoft.com/fwlink/?LinkId=112408)